language: node_js
node_js:
- 0.1
notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
env:
  global:
  - secure: aNlM6xaQ8q0XotMnY3UJRpZuEXSHABxYag1mhxVd7QiBtnS9McD++xyeW71aBlOToMQD+Er/ZJoX5ZVaXefW34CeHEKR/IVggUIevyO2zIQE/WAK6PjwFMMryQcJSSUfBN8+8nbLOEVv4fpw3GuObOVuDC6ZsbOkgzkVEPOp9I0=
  - secure: HpSaah4cOX/OxbMvzJ9OLvHKP38cah1DRB6LBWjKsUMKuT/Jq2kb+w4cF2RSUv96sxmLNITiwUg1azSZvu7gd1qU8BMYPZzD0qiYkoVt3QzXp1MrvvGcvaYpgE7NPHSTbE/DSDi29r/CKWcuquX22j4hh6FplXxgezZaEbz0y8Y=
